package conn;


/**
* conn/Conn.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Conn.idl
* 4 декабря 2018 г. 10:28:14 MSK
*/

public interface Conn extends ConnOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Conn
